- job:
    name: mistral-devstack-tempest-base
    parent: devstack-tempest
    pre-run: playbooks/tempest/pre.yaml
    timeout: 9000
    required-projects:
      - openstack/devstack
      - openstack/devstack-gate
      - openstack/heat
      - openstack/mistral
      - openstack/mistral-lib
      - openstack/mistral-tempest-plugin
      - openstack/python-mistralclient
      - openstack/tempest
      - openstack/zaqar
      - openstack/python-zaqarclient
    vars:
      tox_envlist: all
      tempest_test_regex: mistral
      devstack_localrc:
        TEMPEST_PLUGINS: "{{ ansible_user_dir }}/src/opendev.org/openstack/mistral-tempest-plugin"
        SWIFT_HASH: secrethash
        MYSQL_ROOT_PW: secretdatabase
        MISTRAL_USE_MOD_WSGI: true
        MISTRAL_RPC_IMPLEMENTATION: oslo
        USE_PYTHON3: true
      devstack_services:
        heat: true
        h-api: true
        h-api-cfn: true
        h-api-cw: true
        h-eng: true
        s-proxy: true
        s-object: true
        s-container: true
        s-account: true
        tempest: true
      devstack_plugins:
        mistral: https://opendev.org/openstack/mistral
        heat: https://opendev.org/openstack/heat
        zaqar: https://opendev.org/openstack/zaqar

- job:
    name: mistral-devstack
    parent: mistral-devstack-tempest-base

- job:
    name: mistral-devstack-kombu
    parent: mistral-devstack-tempest-base
    vars:
      devstack_localrc:
        MISTRAL_RPC_IMPLEMENTATION: kombu

- job:
    name: mistral-devstack-non-apache
    parent: mistral-devstack-tempest-base
    vars:
      devstack_localrc:
        MISTRAL_USE_MOD_WSGI: false

- project:
    templates:
      - build-openstack-docs-pti
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - mistral-devstack
        - mistral-devstack-non-apache:
            branches: ^(?!stable/(newton|ocata)).*$
        - mistral-devstack-kombu:
            branches: ^(?!stable/newton).*$
    gate:
      queue: mistral
      jobs:
        - mistral-devstack
        - mistral-devstack-non-apache
        - mistral-devstack-kombu
