- job:
    name: mistral-devstack-tempest-base
    parent: devstack-tempest
    pre-run: playbooks/tempest/pre.yaml
    timeout: 9000
    required-projects: &base_required_projects
      - openstack/devstack
      - openstack/heat
      - openstack/mistral
      - openstack/mistral-lib
      - openstack/mistral-extra
      - openstack/mistral-tempest-plugin
      - openstack/python-mistralclient
      - openstack/tempest
    vars: &base_vars
      tox_envlist: all
      tempest_test_regex: mistral
      devstack_localrc:
        TEMPEST_PLUGINS: "/opt/stack/mistral-tempest-plugin"
        SWIFT_HASH: secrethash
        MYSQL_ROOT_PW: secretdatabase
      devstack_services:
        heat: true
        h-api: true
        h-api-cfn: true
        h-api-cw: true
        h-eng: true
        s-proxy: true
        s-object: true
        s-container: true
        s-account: true
        tempest: true
      devstack_plugins:
        mistral: https://opendev.org/openstack/mistral
        heat: https://opendev.org/openstack/heat

- job:
    name: mistral-devstack-tempest-ipv6-only
    parent: devstack-tempest-ipv6
    description: |
      Mistral devstack tempest tests job for IPv6-only deployment
    pre-run: playbooks/tempest/pre.yaml
    timeout: 9000
    required-projects: *base_required_projects
    vars: *base_vars

# TODO(tkajinam): Remove this after < 2025.1 all reach EOL
- job:
    name: mistral-devstack-non-apache-tempest-ipv6-only
    parent: mistral-devstack-tempest-ipv6-only
    description: |
      Mistral devstack non apache tempest tests job for IPv6-only deployment
    vars:
      devstack_localrc:
        MISTRAL_USE_MOD_WSGI: false

- job:
    name: mistral-devstack
    parent: mistral-devstack-tempest-base

# TODO(gmann): As per the 2025.1 testing runtime, we need to run at least
# one job on jammy. This job run on 2025.1 gate so remove once that is EOL.
- job:
    name: mistral-devstack-jammy
    description: This is integrated job testing on Ubuntu jammy(22.04)
    parent: mistral-devstack
    nodeset: openstack-single-node-jammy

# TODO(tkajinam): Remove this after < 2025.1 all reach EOL
- job:
    name: mistral-devstack-kombu
    parent: mistral-devstack-tempest-base
    vars:
      devstack_localrc:
        MISTRAL_RPC_IMPLEMENTATION: kombu

# TODO(tkajinam): Remove this after < 2025.1 all reach EOL
- job:
    name: mistral-devstack-non-apache
    parent: mistral-devstack-tempest-base
    vars:
      devstack_localrc:
        MISTRAL_USE_MOD_WSGI: false

- project:
    templates:
      - build-openstack-docs-pti
      - check-requirements
      - tempest-plugin-jobs
    check:
      jobs:
        - mistral-devstack
        - mistral-devstack-tempest-ipv6-only
    queue: mistral
    gate:
      jobs:
        - mistral-devstack
        - mistral-devstack-tempest-ipv6-only
